version: '3.8'

volumes:
  solardata:

services:
  frontend: # Renamed from solar-power-app
    build:
      context: .
      dockerfile: Dockerfile # This is the existing Dockerfile for Nginx frontend
    ports:
      - "3000:80" # Nginx still serves on port 80 internally
    container_name: solar-power-frontend
    restart: unless-stopped
    depends_on:
      - backend
    # environment: # NODE_ENV=production is often set in the Dockerfile itself for frontend builds
      # - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: solar-power-backend
    restart: unless-stopped
    volumes:
      - solardata:/app/data # Mount the named volume
    # environment: # Add if server.js needs env vars like GEMINI_API_KEY
    #   - NODE_ENV=production
    # Expose 3001 if direct access needed, otherwise Nginx handles it
    # ports:
    #   - "3001:3001"

  # solar-power-dev service remains for frontend dev, but won't include backend logic
  solar-power-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
    container_name: solar-power-logger-dev
    profiles:
      - dev
